---

- hosts:
    - dhcpd
  become: true
  roles:
     - role: debops.dhcpd
       tags: dhcpd
       dhcpd_ipversion: '4'
       dhcpd_mode: 'server'
       dhcpd_authoritative: true
       dhcpd_interfaces: 
           - enp3s0
           - enp3s0.20
           - enp3s0.40
       dhcpd_hosts:
           - hostname: 'srv-02'
             address: '10.88.0.2, 10.88.16.2, 10.88.32.2'
             ethernet: 'e0:db:55:e1:cd:98'
           - hostname: 'srv-03'
             address: '10.88.0.3, 10.88.16.3, 10.88.32.3'
             ethernet: 'b8:ca:3a:d3:2c:3b'
           - hostname: 'srv-04'
             address: '10.88.0.4, 10.88.16.4, 10.88.32.4'
             ethernet: 'f0:1f:af:22:3a:55'
           - hostname: 'srv-05'
             address: '10.88.0.5, 10.88.16.5, 10.88.32.5'
             ethernet: 'f0:1f:af:2f:2f:9e'
           - hostname: 'srv-06'
             address: '10.88.0.6, 10.88.16.6, 10.88.32.6'
             ethernet: 'd4:be:d9:87:b8:23'
           - hostname: 'sw-01'
             address: '10.88.16.100'
             ethernet: '14:91:82:ec:8e:17'
           - hostname: 'ap-01'
             address: '10.88.16.101'
             ethernet: 'd4:6e:0e:79:e6:be'
           - hostname: 'rpi-01'
             address: '10.88.0.102, 10.88.16.102'
             ethernet: 'b8:27:eb:49:b0:4c'

       dhcpd_subnets:
             - subnet: '10.88.0.0'
               netmask: '255.255.240.0'
               routers: '10.88.0.1'
               comment: 'Cluster public network'
               pools:
                   - range: '10.88.15.1 10.88.15.254'
               options: |
                   option domain-name-servers 8.8.8.8, 8.8.4.4;
                   option domain-name "public.cluster.matthijsbos.nl";
             - subnet: '10.88.16.0'
               netmask: '255.255.240.0'
               comment: 'Cluster management network'
               pools:
                   - range: '10.88.31.1 10.88.31.254'
               options: |
                   option domain-name "management.cluster.matthijsbos.nl";
             - subnet: '10.88.32.0'
               netmask: '255.255.240.0'
               comment: 'Cluster storage network'
               pools:
                   - range: '10.88.47.1 10.88.47.254'
               options: |
                   option domain-name "storage.cluster.matthijsbos.nl";

