---
- hosts: 
      - gateway
  become: true
  tasks:
      - sysctl:
            name: net.ipv4.ip_forward
            value: 1
            sysctl_set: yes
      # enp3s0.10 = WAN network
      # enp3s0.20 = public network
      # enp3s0.30 = management network
      - iptables:
          table: 'nat'
          action: 'append'
          chain: 'POSTROUTING'
          out_interface: 'enp3s0.10'
          jump: 'MASQUERADE'
      - iptables:
          action: 'append'
          chain: 'FORWARD'
          in_interface: 'enp0s17'
          out_interface: 'enp0s18'
          match: 'state'
          ctstate:
              - 'ESTABLISHED'
              - 'RELATED'
          jump: 'ACCEPT'
      - iptables:
          action: 'append'
          chain: 'FORWARD'
          jump: 'ACCEPT'
          in_interface: 'enp0s18'
          out_interface: 'enp0s17'
