---
- hosts:
    - all
  become: true
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        line: 'matthijsbos ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
