---
- hosts: compute-nodes
  become: true
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        line: '{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
